services:
  # ====================================================================================================================
  # RABBITMQ SERVER
  # ====================================================================================================================
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - felipe-network
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q check_running" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  postgresql:
    image: postgres:15-alpine
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: cupomminer
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - felipe-network

  # ====================================================================================================================
  # WIREMOCK SERVER
  # ====================================================================================================================
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: wiremock
    volumes:
      - ./extensions:/var/wiremock/extensions
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
    ports:
      - 8081:8080
    entrypoint: >
      /bin/sh -c "
      rm -rf /home/wiremock/mappings/* &&
      echo '{
        \"request\": {
          \"urlPathPattern\": \"/api/products/4565156131\",
          \"method\": \"GET\"
        },
        \"response\": {
          \"status\": 200,
          \"body\": \"{\\\"ean\\\":4565156131,\\\"ProductName\\\":\\\"Sabão Líquido OMO Lavagem Perfeita 500ml\\\",\\\"minPrice\\\":5,\\\"maxPrice\\\":25.35}\",
          \"headers\": {
            \"Content-Type\": \"application/json\"
          }
        }
      }' > /home/wiremock/mappings/ValidProduct.json &&
      echo '{
        \"request\": {
          \"urlPathPattern\": \"/api/products/([0-9]+)\",
          \"method\": \"GET\"
        },
        \"response\": {
          \"status\": 404,
          \"body\": \"{\\\"error\\\":\\\"Product not found\\\"}\",
          \"headers\": {
            \"Content-Type\": \"application/json\"
          }
        }
      }' > /home/wiremock/mappings/InvalidProduct.json &&
      /docker-entrypoint.sh"
    networks:
      - felipe-network

  # ====================================================================================================================
  # CUPOMMINER SERVER
  # ====================================================================================================================
  cupomminer:
    image: felipesoulsa/cupomminer:1.1.0
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/cupomminer
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_AMQP_DESERIALIZATION_TRUST_ALL: true

    depends_on:
      - postgresql
      - rabbitmq
      - wiremock
    ports:
      - 8080:8080

    networks:
      - felipe-network

volumes:
  postgres-data:

networks:
  felipe-network:
    driver: bridge
